-- This migration creates the media table

CREATE TABLE media (
  id SERIAL PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  type VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);